allowBuilds:
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  zipfile: true

ignoredBuiltDependencies: []

onlyBuiltDependencies: '["onnxruntime-node","protobufjs","sharp"]'
